services:
  apache:
    image: 'ubuntu/apache2:2.4-22.04_beta'
    ports:
      - 8082:80
    volumes:
      - ./html:/var/www/html
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
