services:
  web:
    container_name: web_container
    image: 'httpd:latest'
    ports:
      - '8080:80'
    volumes:
      - ./docker/html:/var/www/html
      - ./docker/html_config/httpd.conf:/usr/local/apache2/conf/httpd.conf
  postgres:
    container_name: postgres_container
    volumes:
      - ./docker/postgres/logs:/var/log/postgresql
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mediasalpes'
      - 'POSTGRES_PASSWORD=mediaspassword'
      - 'POSTGRES_USER=mediasadmin'
    ports:
      - '5432:5432'
  pgadmin:
    container_name: pgadmin_container
    image: 'dpage/pgadmin4:latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: mediasmaintenance@local.int
      PGADMIN_DEFAULT_PASSWORD: mediaspassword
    volumes:
      - /docker/pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - '8090:80'
  javaspring:
    container_name: java_spring_container
    restart: unless-stopped
    build:
      context: .
    ports:
      - '9191:9191'
