services:
  web:
    container_name: web_container
    image: 'ubuntu/apache2:2.4-22.04_beta'
    ports:
      - 8080:80
    volumes:
      - ./docker/html:/var/www/html
  postgres:
    container_name: postgres_container
    volumes:
      - ./docker/postgres/logs:/var/log/postgresql
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mediasalpes'
      - 'POSTGRES_PASSWORD=mediaspassword'
      - 'POSTGRES_USER=mediasadmin'
    ports:
      - '5432:5432'
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.6
    environment:
      PGADMIN_DEFAULT_EMAIL: mediasmaintenance@local.int
      PGADMIN_DEFAULT_PASSWORD: mediaspassword
      PGADMIN_SERVER_JSON_FILE: ./docker/pgadmin/server.json
    volumes:
      - ./docker/pgadmin:/root/.pgadmin
    ports:
      - 8090:80
  spring:
    container_name: spring_container
    build:
      context: .
    ports:
      - 8081:8080
