services:
  app:
    container_name: web_container
    image: 'ubuntu/apache2:2.4-22.04_beta'
    ports:
      - 8080:80
    volumes:
      - ./html:/var/www/html
  postgres:
    container_name: postgres_container
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.6
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@local.int
      PGADMIN_DEFAULT_PASSWORD: changeme
      PG_DATABASE: simple-course
      PG_USER: postgres
      PG_PASSWORD: changeme
    volumes:
      - ./docker/pgadmin:/root/.pgadmin
    ports:
      - 8090:80
  spring:
    container_name: spring_container
    build:
      context: .
    ports:
      - 8081:8080
