openapi: 3.0.0
info:
  title: MediasAlpes
  version: '1.0'
  description: Medias des Alpes
  contact:
    name: Mathis
servers:
  - url: 'http://localhost:9191'
paths:
  /version:
    get:
      summary: Version de Postgres
      tags:
        - version
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
      operationId: get-version
      description: 'Renvoie la version de Postgres, sert à vérifier surtout que la BDD répond.'
  /utilisateur/liste:
    get:
      summary: Liste de tous les noms et prénoms
      tags:
        - utilisateur
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
      operationId: get-utilisateur-liste
      description: Renvoie la Liste.
components:
  schemas: {}
tags:
  - name: version
