openapi: 3.0.0
info:
  title: MediasAlpes
  version: '1.0'
  description: Medias des Alpes
  contact:
    name: Mathis
servers:
  - url: 'http://localhost:9191'
paths:
  '/medias/{idMedia}':
    parameters:
      - schema:
          type: integer
        name: idMedia
        in: path
    get:
      summary: Récupère un média par son ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Media'
      operationId: get-media-by-id
      description: ''
      tags:
        - media
components:
  schemas:
    Utilisateur:
      title: Utilisateur
      type: object
      properties:
        id:
          type: string
      x-tags:
        - utilisateur
    Media:
      title: Media
      type: object
      x-tags:
        - media
      properties:
        idMedia:
          type: integer
        titre:
          type: string
        idType:
          $ref: '#/components/schemas/TypeMedia'
        idGenre:
          $ref: '#/components/schemas/GenreMedia'
        idAuteur:
          $ref: '#/components/schemas/Auteur'
        anneePublicationSortie:
          type: integer
        noteMedia:
          type: number
        imgMedia:
          type: string
      required:
        - idMedia
    GenreMedia:
      title: Genre
      type: object
      x-tags:
        - media
      properties:
        idGenre:
          type: string
        designation:
          type: string
    TypeMedia:
      title: Type
      type: object
      x-tags:
        - media
      properties:
        idType:
          type: integer
        designationType:
          type: string
        designationAuteur:
          type: string
    NationaliteAuteur:
      title: Auteur
      type: object
      x-tags:
        - media
      properties:
        idNationalite:
          type: number
        designation:
          type: string
    Auteur:
      title: Nationalite
      type: object
      x-tags:
        - media
      properties:
        idAuteur:
          type: integer
        nomAuteur:
          type: string
        prenomAuteur:
          type: string
        nationaliteAuteur:
          $ref: '#/components/schemas/NationaliteAuteur'
tags:
  - name: version
