openapi: 3.0.0
info:
  title: MediasAlpes
  version: '1.0'
  description: Medias des Alpes
  contact:
    name: Mathis
servers:
  - url: 'http://localhost:9191'
paths:
  '/media/{idMedia}':
    parameters:
      - schema:
          type: integer
        name: idMedia
        in: path
        required: true
    get:
      summary: Récupère un média par son ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Media'
        '404':
          description: Not Found
      operationId: get-media-by-id
      description: ''
      tags:
        - media
components:
  schemas:
    Utilisateur:
      title: Utilisateur
      type: object
      properties:
        id:
          type: string
      x-tags:
        - utilisateur
    Media:
      title: Media
      type: object
      x-tags:
        - media
      properties:
        id:
          type: integer
        titre:
          type: string
        type:
          $ref: '#/components/schemas/TypeMedia'
        genre:
          $ref: '#/components/schemas/GenreMedia'
        auteurs:
          type: array
          items:
            $ref: '#/components/schemas/Auteur'
        anneePublicationSortie:
          type: integer
        note:
          type: number
        img:
          type: string
      required:
        - id
    GenreMedia:
      title: Genre
      type: object
      x-tags:
        - media
      properties:
        id:
          type: string
        designation:
          type: string
    TypeMedia:
      title: Type
      type: object
      x-tags:
        - media
      properties:
        id:
          type: integer
        designationType:
          type: string
        designationAuteur:
          type: string
    NationaliteAuteur:
      title: NationaliteAuteur
      type: object
      x-tags:
        - auteur
      properties:
        id:
          type: integer
        designation:
          type: string
    Auteur:
      title: Auteur
      type: object
      properties:
        id:
          type: integer
        nom:
          type: string
        prenom:
          type: string
        nationalite:
          $ref: '#/components/schemas/NationaliteAuteur'
      x-tags:
        - auteur
