openapi: 3.0.0
info:
  title: MediasAlpes
  version: '1.0'
  description: Medias des Alpes
  contact:
    name: Mathis
servers:
  - url: 'http://localhost:9191'
paths:
  '/medias/{idMedia}':
    parameters:
      - schema:
          type: integer
        name: idMedia
        in: path
        required: true
    get:
      summary: Récupère un média par son ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Media'
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: get-media-by-id
      description: ''
      tags:
        - medias
  /medias:
    get:
      summary: Récupère tous les médias
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Media'
      operationId: get-media
      tags:
        - medias
    parameters: []
  /utilisateurs:
    post:
      summary: Tous les utilisateurs
      operationId: post-user-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtResponse'
        '500':
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConnexionForm'
      tags:
        - utilisateurs
    parameters: []
  /connexion:
    post:
      summary: Connexion
      operationId: post-connexion
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConnexionForm'
        description: ''
      tags:
        - connexion
    parameters: []
  /inscription:
    post:
      summary: Inscription
      operationId: post-inscription
      responses:
        '201':
          description: Created
        '302':
          description: Found
        '406':
          description: Not Acceptable
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Utilisateur'
        description: ''
      tags:
        - inscription
components:
  schemas:
    Utilisateur:
      title: Utilisateur
      type: object
      x-tags:
        - utilisateurs
      properties:
        emailUtilisateur:
          type: string
        mdpUtilisateur:
          type: string
        nomUtilisateur:
          type: string
        prenomUtilisateur:
          type: string
        adresseUtilisateur:
          type: string
        numTelephoneUtilisateur:
          type: string
        dateNaissanceUtilisateur:
          type: string
    Media:
      title: Media
      type: object
      x-tags:
        - medias
      properties:
        id:
          type: integer
        titre:
          type: string
        type:
          $ref: '#/components/schemas/TypeMedia'
        genre:
          $ref: '#/components/schemas/GenreMedia'
        auteurs:
          type: array
          items:
            $ref: '#/components/schemas/Auteur'
        anneePublicationSortie:
          type: integer
        note:
          type: number
        img:
          type: string
      required:
        - id
    GenreMedia:
      title: Genre
      type: object
      x-tags:
        - medias
      properties:
        id:
          type: string
        designation:
          type: string
    TypeMedia:
      title: Type
      type: object
      x-tags:
        - medias
      properties:
        id:
          type: integer
        designationType:
          type: string
        designationAuteur:
          type: string
    NationaliteAuteur:
      title: NationaliteAuteur
      type: object
      x-tags:
        - auteurs
      properties:
        id:
          type: integer
        designation:
          type: string
    Auteur:
      title: Auteur
      type: object
      properties:
        id:
          type: integer
        nom:
          type: string
        prenom:
          type: string
        nationalite:
          $ref: '#/components/schemas/NationaliteAuteur'
      x-tags:
        - auteurs
    ConnexionForm:
      title: ConnexionForm
      type: object
      properties:
        login:
          type: string
        password:
          type: string
      x-tags:
        - connexion
    JwtResponse:
      title: JwtResponse
      type: object
      properties:
        token:
          type: string
